const palette = {
    primaryDark: '#1B3C53',
    primary: '#234C6A',
    primaryLight: '#456882',
    successDark: '#15803d',
    success: '#16a34a',
    successLight: '#22c55e',
    errorDark: '#ef4444',
    errorLight: '#f87171',
    textDark: '#111',
    textLight: '#fff',
    textMutedDark: '#11111160',
    textMutedLight: '#ffffff60',
    borderDark: '#D0D0D0',
    borderLight: '#4B4B4B',
    surfaceDark: '#fff',
    surfaceLight: '#111',
    buttonDark: '#111',
    buttonLight: '#f5f5f5',
    onButtonDark: '#fff',
    onButtonLight: '#111',
    white: '#fff',
};

export default {
    light: {
        text: palette.textDark,
        textMuted: palette.textMutedDark,
        tint: palette.primary,
        border: palette.borderDark,
        surface: palette.surfaceDark,
        button: palette.buttonDark,
        onButton: palette.onButtonDark,
        error: palette.errorDark,
        success: palette.successDark,
        headerBackground: palette.primary,
        white: palette.white,
    },
    dark: {
        text: palette.textLight,
        textMuted: palette.textMutedLight,
        tint: palette.primary,
        border: palette.borderLight,
        surface: palette.surfaceLight,
        button: palette.buttonLight,
        onButton: palette.onButtonLight,
        error: palette.errorLight,
        success: palette.successLight,
        headerBackground: palette.primaryLight,
        white: palette.white,
    },
};
